Models/Jogos.cs
using System.ComponentModel.DataAnnotations;

namespace AsMinhasReviews.Models
{
    /// <summary>
    /// Representa os dados do jogo
    /// </summary>
    public class Jogos
    {
        public Jogos()
        {
            ListaReviews = new HashSet<Reviews>();
        }

        /// <summary>
        /// Chave primária da tabela dos jogos
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Nome do Jogo
        /// </summary>
        [Required(ErrorMessage = "O nome do jogo é de preenchimento obrigatório.")]
        public string Nome { get; set; }

        public string NomeFormatado { get; set; }

        /// <summary>
        /// Capa do Jogo
        /// </summary>
        public string Capa { get; set; }

        /// <summary>
        /// Plataformas do Jogo
        /// </summary>
        [Required(ErrorMessage = "A plataforma do jogo é de preenchimento obrigatório.")]
        public string Plataformas { get; set; }

        /// <summary>
        /// Data de lançamento do Jogo
        /// </summary>
        [Required(ErrorMessage = "A data de lançamento do jogo é de preenchimento obrigatório.")]
        [Display(Name = "Data de lançamento")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DataLancamento { get; set; }

        /// <summary>
        /// Descrição do jogo
        /// </summary>
        [Required(ErrorMessage = "A descrição do jogo é de preenchimento obrigatório.")]
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }

        /// <summary>
        /// Rating do jogo
        /// </summary>
        [DisplayFormat(DataFormatString = "{0:0.0}")]  
        public decimal Rating { get; set; }

        /// <summary>
        /// Lista de reviews do jogo
        /// </summary>
        public ICollection<Reviews> ListaReviews { get; set; }
    }
}

Controllers/ReviewsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AsMinhasReviews.Data;
using AsMinhasReviews.Models;

namespace AsMinhasReviews.Controllers
{
    public class ReviewsController : Controller
    {
        /// <summary>
        /// Manipula os dados da base de dados
        /// </summary>
        private readonly ApplicationDbContext _context;

        public ReviewsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Reviews
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Reviews.Include(r => r.Criador).Include(r => r.Jogo);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Reviews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Reviews == null)
            {
                return NotFound();
            }
            //Inclui informação sobre o criador da review e sobre o jogo para o qual a review é feita na vista detalhada dessa review
            var reviews = await _context.Reviews
                .Include(r => r.Criador)
                .Include(r => r.Jogo)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reviews == null)
            {
                return NotFound();
            }

            return View(reviews);
        }

        // GET: Reviews/Create
        public IActionResult Create()
        {
            //Mostra os jogos ordenados por nome na dropdown da vista de criação da review
            ViewData["JogoFK"] = new SelectList(_context.Jogos, "Id", "Nome").OrderBy(c => c.Text);
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DataCriacao,Conteudo,Rating,CriadorFK,JogoFK")] Reviews review)
        {
            //Atribuir o id do criador e a data de criação da review à review em si
            var utilizador = _context.Utilizadores.FirstOrDefault(u => u.Nome == User.Identity.Name);
            review.CriadorFK = utilizador.Id;
            review.DataCriacao = DateTime.Now;
            if (ModelState.IsValid)
            {
                _context.Add(review);
                //Atualizar o rating do jogo tendo em conta a review criada pelo utilizador
                var average = await _context.Reviews.Where(r => r.JogoFK == review.JogoFK).AverageAsync(r => r.Rating);
                Jogos j = await _context.Jogos.FirstOrDefaultAsync(j => j.Id == review.JogoFK);
                j.Rating = (decimal)average;
                await _context.SaveChangesAsync();
                //Determinar a página para a qual o utilizador será redirecionado
                var route = new RouteValueDictionary {
                    { "id", review.Id } };
                return RedirectToAction(nameof(Details), nameof(Reviews), route);
            }
            return View(review);
        }

        // GET: Reviews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Reviews == null)
            {
                return NotFound();
            }
            var reviews = await _context.Reviews.FindAsync(id);
            if (reviews == null)
            {
                return NotFound();
            }
            ViewData["CriadorFK"] = new SelectList(_context.Utilizadores, "Id", "Nome", reviews.CriadorFK);
            ViewData["JogoFK"] = new SelectList(_context.Jogos, "Id", "Capa", reviews.JogoFK);
            return View(reviews);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DataCriacao,Conteudo,Rating,CriadorFK,JogoFK")] Reviews review)
        {
            //Determinar a página para a qual o utilizador será redirecionado
            var route = new RouteValueDictionary {
                    { "id", review.Id } };
            if (id != review.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _context.Update(review);
                _context.SaveChanges();
                //Atualizar o rating do jogo tendo em conta a review criada pelo utilizador
                var average = await _context.Reviews.Where(r => r.JogoFK == review.JogoFK).AverageAsync(r => r.Rating);
                Jogos j = await _context.Jogos.FirstOrDefaultAsync(j => j.Id == review.JogoFK);
                j.Rating = (decimal)average;
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Details), nameof(Reviews), route);
            }
            return View(review);
        }

        // GET: Reviews/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Reviews == null)
            {
                return NotFound();
            }
            //Inclui informação sobre o criador da review e sobre o jogo para o qual a review é feita na vista detalhada dessa review
            var reviews = await _context.Reviews
                .Include(r => r.Criador)
                .Include(r => r.Jogo)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reviews == null)
            {
                return NotFound();
            }

            return View(reviews);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Reviews == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Reviews'  is null.");
            }
            var review = await _context.Reviews.FindAsync(id);
            //Determinar a página para a qual o utilizador será redirecionado
            var route = new RouteValueDictionary {
                { "id", review.JogoFK } };
            if (review != null)
            {
                _context.Reviews.Remove(review);
                _context.SaveChanges();
            }
            //Atualizar o rating do jogo tendo em conta a review criada pelo utilizador
            var average = await _context.Reviews.Where(r => r.JogoFK == review.JogoFK).AverageAsync(r => r.Rating);
            Jogos j = await _context.Jogos.FirstOrDefaultAsync(j => j.Id == review.JogoFK);
            j.Rating = (decimal)average;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Details), nameof(Jogos),route);
        }

        private bool ReviewsExists(int id)
        {
          return _context.Reviews.Any(e => e.Id == id);
        }
    }
}

Controllers/UtilizadoresController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AsMinhasReviews.Data;
using AsMinhasReviews.Models;

namespace AsMinhasReviews.Controllers
{
    public class UtilizadoresController : Controller
    {
        /// <summary>
        /// Manipula os dados da base de dados
        /// </summary>
        private readonly ApplicationDbContext _context;

        public UtilizadoresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Utilizadores
        public async Task<IActionResult> Index()
        {
              return View(await _context.Utilizadores.ToListAsync());
        }

        // GET: Utilizadores/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Utilizadores == null)
            {
                return NotFound();
            }
            //Inclui a lista de reviews referente ao jogo na vista detalhada desse mesmo jogo
            var utilizadores = await _context.Utilizadores
                .Include(u => u.ListaReviews)
                    .ThenInclude(r => r.Jogo)
                .Where(u => u.Nome == id)
                .FirstOrDefaultAsync(m => m.Nome == id);

            if (utilizadores == null)
            {
                return NotFound();
            }

            return View(utilizadores);
        }

        // GET: Utilizadores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Utilizadores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,DataNascimento,UserID")] Utilizadores utilizadores)
        {
            if (ModelState.IsValid)
            {
                _context.Add(utilizadores);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(utilizadores);
        }

        // GET: Utilizadores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Utilizadores == null)
            {
                return NotFound();
            }

            var utilizadores = await _context.Utilizadores.FindAsync(id);
            if (utilizadores == null)
            {
                return NotFound();
            }
            return View(utilizadores);
        }

        // POST: Utilizadores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,DataNascimento,UserID")] Utilizadores utilizadores)
        {
            if (id != utilizadores.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(utilizadores);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UtilizadoresExists(utilizadores.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(utilizadores);
        }

        // GET: Utilizadores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Utilizadores == null)
            {
                return NotFound();
            }

            var utilizadores = await _context.Utilizadores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (utilizadores == null)
            {
                return NotFound();
            }

            return View(utilizadores);
        }

        // POST: Utilizadores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Utilizadores == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Utilizadores'  is null.");
            }
            var utilizadores = await _context.Utilizadores.FindAsync(id);
            if (utilizadores != null)
            {
                _context.Utilizadores.Remove(utilizadores);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UtilizadoresExists(int id)
        {
          return _context.Utilizadores.Any(e => e.Id == id);
        }
    }
}

Views/Jogos/Create.cshtml
@model AsMinhasReviews.Models.Jogos
@{
    ViewData["Title"] = "Criar Jogo";
}
@if (User.IsInRole("Administrador"))
{
    <h1>Criar jogo</h1>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Capa" class="control-label"></label>
                    <input type="file" name="capaJogo" class="form-control" accept=".jpg,.png" />
                    <span asp-validation-for="Capa" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Plataformas" class="control-label"></label>
                    <input asp-for="Plataformas" class="form-control" />
                    <span asp-validation-for="Plataformas" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DataLancamento" class="control-label"></label>
                    <input asp-for="DataLancamento" class="form-control" />
                    <span asp-validation-for="DataLancamento" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Descricao" class="control-label"></label>
                    <textarea asp-for="Descricao" class="form-control" rows="5"></textarea>
                    <span asp-validation-for="Descricao" class="text-danger"></span>
                </div>
                <p style="margin-bottom:0px;">Fotografias</p>
                <div class="form-group">
                    <input type="file" name="Fotos" class="form-control" accept=".jpg,.png" multiple="multiple"/>
                    <span asp-validation-for="Capa" class="text-danger"></span>
                </div>
                <br>
                <div class="form-group">
                    <input type="submit" value="Criar" class="btn btn-primary"/>
                </div>
            </form>
        </div>
    </div>
}
else
{
    <p>A criação de jogos apenas é reservada aos administradores.</p>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Jogos/Delete.cshtml
@model AsMinhasReviews.Models.Jogos
@inject IWebHostEnvironment env
@{
    ViewData["Title"] = "Remover jogo";
}
@if (User.IsInRole("Administrador"))
{
<h1>Remover jogo</h1>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capa)
        </dt>
        <dd class = "col-sm-10">
            <img src="~/Fotos/@Html.DisplayFor(model => model.Capa)"
                         alt="Foto de model.Nome"
                         title="model.Nome"
                         height="175px" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Plataformas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Plataformas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataLancamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataLancamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            Fotografias
        </dt>
        <dd class = "col-sm-10">
            @{
        int i = 0;
        while(true){
            i++;
            var aux = Model.NomeFormatado + i + ".png";
            if (System.IO.File.Exists(System.IO.Path.Combine(env.WebRootPath,"Fotos\\" + Model.NomeFormatado + i + ".png")))
            {
                aux = Model.NomeFormatado + i + ".png";
                <img src="~/Fotos/@Html.DisplayFor(model => aux)" height="175px" />
            }
            else if (System.IO.File.Exists(System.IO.Path.Combine(env.WebRootPath,"Fotos\\" + Model.NomeFormatado + i + ".jpg")))
            {
                aux = Model.NomeFormatado + i + ".jpg";
                <img style="margin-bottom:10px" src="~/Fotos/@Html.DisplayFor(model => aux)" height="175px" />
            }
            else
            {
                break;
            }
        }
    }
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Remover" class="btn btn-danger" />
    </form>
</div>
}
else
{
    <p>A remoção de jogos apenas é reservada aos administradores.</p>
}

Views/Jogos/Details.cshtml
@model AsMinhasReviews.Models.Jogos
@inject IWebHostEnvironment env
@{
    ViewData["Title"] = "Detalhes do jogo";
}
<div>
    <table class="table">
        <tbody>
            <tr height="225px;">
                <td style="padding-left:0px; padding-top: 0px;">
                    <img src="~/Fotos/@Html.DisplayFor(model => model.Capa)"
                         alt="Foto de model.Nome"
                         title="model.Nome"
                         height="175px" />
                </td>
                <td>
                    <div class="listarating" style="float: right">@Html.DisplayFor(model => model.Rating) <img src="~/Fotos/estrela.png" height="22.5px" style="margin-bottom:7.5px;" /></div>
                    @{var Datalanc = Model.DataLancamento.ToLongDateString();}
                    <div class="listainfo">Plataformas: @Html.DisplayFor(model => model.Plataformas)<br>@Datalanc</div>
                    <div class="listadesc">@Html.DisplayFor(model => model.Descricao)</div>
                </td>
            </tr>
        </tbody>
    </table>
    <h3>Fotografias</h3>
    @{
        int i = 0;
        while(true){
            i++;
            var aux = Model.NomeFormatado + i + ".png";
            if (System.IO.File.Exists(System.IO.Path.Combine(env.WebRootPath,"Fotos\\" + Model.NomeFormatado + i + ".png")))
            {
                aux = Model.NomeFormatado + i + ".png";
                        <img src="~/Fotos/@Html.DisplayFor(model => aux)" height="175px" />
            }
            else if (System.IO.File.Exists(System.IO.Path.Combine(env.WebRootPath,"Fotos\\" + Model.NomeFormatado + i + ".jpg")))
            {
                aux = Model.NomeFormatado + i + ".jpg";
                        <img src="~/Fotos/@Html.DisplayFor(model => aux)" height="175px" />
            }
            else
            {
                break;
            }
        }
    }
    <hr />
    <h3>Reviews</h3>
    <table class="table">
        @foreach (var review in Model.ListaReviews ?? Enumerable.Empty<Reviews>())
        {
            <tr>
                <td style="padding-left:0px; padding-right:8px;">
                    <div class="listarating" style="float: right">@review.Rating <img src="~/Fotos/estrela.png" height="22.5px" style="margin-bottom:7.5px;" /></div>
                    <div class="listainfo"><a class="textouser" asp-controller="Utilizadores" asp-action="Details" asp-route-id="@review.Criador.Nome">@review.Criador.Nome</a></div>
                    <div class="listadesc"><a class="textoreview" asp-controller="Reviews" asp-action="Details" asp-route-id="@review.Id">@review.Conteudo</a></div>
                    <div class="listainfo">@review.DataCriacao.ToLongDateString()</div>
                </td>
            </tr>
        }
    </table>
</div>
@if (User.IsInRole("Administrador"))
{
    <div>
        <a asp-action="Edit" asp-route-id="@Model?.Id">Editar</a> | 
        <a asp-action="Delete" asp-route-id="@Model?.Id">Remover</a>
    </div>
}

Views/Jogos/Edit.cshtml
@model AsMinhasReviews.Models.Jogos

@{
    ViewData["Title"] = "Editar jogo";
}
@if (User.IsInRole("Administrador"))
{
    <h1>Editar jogo</h1>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Capa" class="control-label"></label>
                    <input type="file" name="capaJogo" class="form-control" accept=".jpg,.png" />
                    <span asp-validation-for="Capa" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Plataformas" class="control-label"></label>
                    <input asp-for="Plataformas" class="form-control" />
                    <span asp-validation-for="Plataformas" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DataLancamento" class="control-label"></label>
                    <input asp-for="DataLancamento" class="form-control" />
                    <span asp-validation-for="DataLancamento" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Descricao" class="control-label"></label>
                    <textarea asp-for="Descricao" class="form-control" rows="5"></textarea>
                    <span asp-validation-for="Descricao" class="text-danger"></span>
                </div>
                <p style="margin-bottom:0px;">Fotografias</p>
                <div class="form-group">
                    <input type="file" name="Fotos" class="form-control" accept=".jpg,.png" multiple="multiple"/>
                    <span asp-validation-for="Capa" class="text-danger"></span>
                </div>
                <br>
                <div class="form-group">
                    <input type="submit" value="Guardar" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
}
else
{
    <p>A edição de jogos apenas é reservada aos administradores.</p>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Jogos/Index.cshtml
@model IEnumerable<AsMinhasReviews.Models.Jogos>
@{
    ViewData["Title"] = "Jogos";
}
<h1>Lista de jogos</h1>
@if (User.IsInRole("Administrador"))
{
    <p>
        <a asp-action="Create">Criar jogo</a>
    </p>
}
<hr />
<table class="table">
    <tbody>
        @{
            int i = 0;
        }
        @foreach (var item in Model)
        {
            i = @i + 1;
            <tr height="225px;">
                <td style="padding-left:0px; padding-top: 0px;">
                    <img src="~/Fotos/@Html.DisplayFor(modelItem => item.Capa)"
                     alt="Foto de @item.Nome"
                     title="@item.Nome"
                     height="175px"
                     />
                </td>
                <td>
                    <div class="listarating" style="float: right">@Html.DisplayFor(modelItem => item.Rating) <img src="~/Fotos/estrela.png" height="22.5px" style="margin-bottom:7.5px;"/></div>
                    <div><a class="listatitulo" asp-action="Details" asp-route-id="@item.Id">@i. @Html.DisplayFor(modelItem => item.Nome)</a></div>
                    <div class="listainfo">Plataformas: @Html.DisplayFor(modelItem => item.Plataformas)<br>@item.DataLancamento.ToLongDateString()</div>
                    <div class="listadesc">@Html.DisplayFor(modelItem => item.Descricao)</div>
                </td>
                @if (User.IsInRole("Administrador"))
                {
                    <td width="150px" style="text-align: center;">
                        <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> | 
                        <a asp-action="Delete" asp-route-id="@item.Id">Remover</a>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>