Controllers/JogosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AsMinhasReviews.Data;
using AsMinhasReviews.Models;

namespace AsMinhasReviews.Controllers
{
    public class JogosController : Controller
    {
        /// <summary>
        /// Manipula os dados da base de dados
        /// </summary>
        private readonly ApplicationDbContext _context;

        /// <summary>
        /// Variável que contem os dados do servidor
        /// </summary>
        private readonly IWebHostEnvironment _webHostEnvironment;

        public JogosController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Jogos
        public async Task<IActionResult> Index(string id)
        {
            //Ordena a lista de jogos por rating ou data de lançamento
            switch (id)
            {
                case "Rating":
                    return View(await _context.Jogos.OrderByDescending(j => j.Rating).ToListAsync());
                case "Data":
                    return View(await _context.Jogos.OrderByDescending(j => j.DataLancamento).ToListAsync());
                default:
                    return View(await _context.Jogos.ToListAsync());
            }
        }

        // GET: Jogos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Jogos == null)
            {
                return NotFound();
            }
            //Inclui a lista de reviews referente ao jogo na vista detalhada desse mesmo jogo
            var jogos = await _context.Jogos
                .Include(j => j.ListaReviews)
                    .ThenInclude(r => r.Criador)
                .Where(j => j.Id == id)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jogos == null)
            {
                return NotFound();
            }

            return View(jogos);

        }

        // GET: Jogos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Jogos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Capa,Plataformas,DataLancamento,Descricao,Rating")] Jogos jogo, IFormFile capaJogo, List<IFormFile> fotos)
        {
            //Formata o nome do jogo para letras minúsculas sem espaços
            jogo.NomeFormatado = jogo.Nome.Trim().ToLower();
            //Como o jogo não tem nenhuma review quando é criado, atribuir 0 a esse valor
            jogo.Rating = 0;
            //Se o utilizador não enviou uma capa, definir o valor do atributo como "semCapa.png"
            if (capaJogo == null)
            {
                jogo.Capa = "semCapa.png";
            }
            else
            {
                //Verificar se o ficheiro enviado para a capa é uma imagem
                if (!(capaJogo.ContentType == "image/png" || capaJogo.ContentType == "image/jpeg"))
                {
                    ModelState.AddModelError("", "Por favor, adicione um ficheiro .png ou .jpg");
                    return View(jogo);
                }
                //Atribuir o nome da capa
                else
                {
                    string nomeFoto = (jogo.NomeFormatado + Path.GetExtension(capaJogo.FileName)).ToLower();
                    jogo.Capa = nomeFoto;
                }
            }
            if (ModelState.IsValid)
            {
                //Adicionar o jogo à base de dados
                _context.Add(jogo);
                await _context.SaveChangesAsync();
                //Guardar a imagem da capa enviada no servidor
                if (capaJogo != null)
                {
                    string nomeLocalizacaoFicheiro = _webHostEnvironment.WebRootPath;
                    nomeLocalizacaoFicheiro = Path.Combine(nomeLocalizacaoFicheiro, "Fotos");
                    if (!Directory.Exists(nomeLocalizacaoFicheiro))
                    {
                        Directory.CreateDirectory(nomeLocalizacaoFicheiro);
                    }
                    //Nome do documento a guardar
                    string nomeDaFoto = Path.Combine(nomeLocalizacaoFicheiro, jogo.Capa);
                    //Criar o objeto que vai manipular o ficheiro
                    using var stream = new FileStream(nomeDaFoto, FileMode.Create);
                    //Guardar no disco rígido
                    await capaJogo.CopyToAsync(stream);
                    int i = 0;
                    //Guardar as fotografias do jogo no servidor
                    foreach (IFormFile foto in fotos)
                    {
                        i++;
                        if (foto != null)
                        {
                            nomeLocalizacaoFicheiro = _webHostEnvironment.WebRootPath;
                            nomeLocalizacaoFicheiro = Path.Combine(nomeLocalizacaoFicheiro, "Fotos");
                            if (!Directory.Exists(nomeLocalizacaoFicheiro))
                            {
                                Directory.CreateDirectory(nomeLocalizacaoFicheiro);
                            }
                            //Nome do documento a guardar
                            string nomeFoto = (jogo.NomeFormatado + i + Path.GetExtension(foto.FileName)).ToLower();
                            nomeDaFoto = Path.Combine(nomeLocalizacaoFicheiro, nomeFoto);
                            //Criar o objeto que vai manipular o ficheiro
                            using var stream2 = new FileStream(nomeDaFoto, FileMode.Create);
                            //Guardar no disco rígido
                            await foto.CopyToAsync(stream2);
                        }
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(jogo);
        }

        // GET: Jogos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Jogos == null)
            {
                return NotFound();
            }

            var jogos = await _context.Jogos.FindAsync(id);
            if (jogos == null)
            {
                return NotFound();
            }
            return View(jogos);
        }

        // POST: Jogos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //Processo igual à criação do jogo
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Capa,Plataformas,DataLancamento,Descricao")] Jogos jogo, IFormFile capaJogo, List<IFormFile> fotos)
        {
            jogo.NomeFormatado = jogo.Nome.Trim().ToLower();
            if (capaJogo == null)
            {
                jogo.Capa = "semCapa.png";
            }
            else
            {
                if (!(capaJogo.ContentType == "image/png" || capaJogo.ContentType == "image/jpeg"))
                {
                    ModelState.AddModelError("", "Por favor, adicione um ficheiro .png ou .jpg");
                    return View(jogo);
                }
                else
                {
                    string nomeFoto = (jogo.NomeFormatado + Path.GetExtension(capaJogo.FileName)).ToLower();
                    jogo.Capa = nomeFoto;
                }
            }
            if (ModelState.IsValid)
            {
                _context.Update(jogo);
                await _context.SaveChangesAsync();
                if (capaJogo != null)
                {
                    string nomeLocalizacaoFicheiro = _webHostEnvironment.WebRootPath;
                    nomeLocalizacaoFicheiro = Path.Combine(nomeLocalizacaoFicheiro, "Fotos");
                    if (!Directory.Exists(nomeLocalizacaoFicheiro))
                    {
                        Directory.CreateDirectory(nomeLocalizacaoFicheiro);
                    }
                    //Nome do documento a guardar
                    string nomeDaFoto = Path.Combine(nomeLocalizacaoFicheiro, jogo.Capa);
                    //Criar o objeto que vai manipular o ficheiro
                    using var stream = new FileStream(nomeDaFoto, FileMode.Create);
                    //Guardar no disco rígido
                    await capaJogo.CopyToAsync(stream);
                    int i = 0;
                    foreach (IFormFile foto in fotos)
                    {
                        i++;
                        if (foto != null)
                        {
                            nomeLocalizacaoFicheiro = _webHostEnvironment.WebRootPath;
                            nomeLocalizacaoFicheiro = Path.Combine(nomeLocalizacaoFicheiro, "Fotos");
                            if (!Directory.Exists(nomeLocalizacaoFicheiro))
                            {
                                Directory.CreateDirectory(nomeLocalizacaoFicheiro);
                            }
                            //Nome do documento a guardar
                            string nomeFoto = (jogo.NomeFormatado + i + Path.GetExtension(foto.FileName)).ToLower();
                            nomeDaFoto = Path.Combine(nomeLocalizacaoFicheiro, nomeFoto);
                            //Criar o objeto que vai manipular o ficheiro
                            using var stream2 = new FileStream(nomeDaFoto, FileMode.Create);
                            //Guardar no disco rígido
                            await foto.CopyToAsync(stream2);
                        }
                    }
                }
                return RedirectToAction(nameof(Index));
            }

Controllers/UtilizadoresController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AsMinhasReviews.Data;
using AsMinhasReviews.Models;

namespace AsMinhasReviews.Controllers
{
    public class UtilizadoresController : Controller
    {
        /// <summary>
        /// Manipula os dados da base de dados
        /// </summary>
        private readonly ApplicationDbContext _context;

        public UtilizadoresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Utilizadores
        public async Task<IActionResult> Index()
        {
              return View(await _context.Utilizadores.ToListAsync());
        }

        // GET: Utilizadores/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Utilizadores == null)
            {
                return NotFound();
            }
            //Inclui a lista de reviews referente ao jogo na vista detalhada desse mesmo jogo
            var utilizadores = await _context.Utilizadores
                .Include(u => u.ListaReviews)
                    .ThenInclude(r => r.Jogo)
                .Where(u => u.Nome == id)
                .FirstOrDefaultAsync(m => m.Nome == id);

            if (utilizadores == null)
            {
                return NotFound();
            }

            return View(utilizadores);
        }

        // GET: Utilizadores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Utilizadores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,DataNascimento,UserID")] Utilizadores utilizadores)
        {
            if (ModelState.IsValid)
            {
                _context.Add(utilizadores);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(utilizadores);
        }

        // GET: Utilizadores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Utilizadores == null)
            {
                return NotFound();
            }

            var utilizadores = await _context.Utilizadores.FindAsync(id);
            if (utilizadores == null)
            {
                return NotFound();
            }
            return View(utilizadores);
        }

        // POST: Utilizadores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,DataNascimento,UserID")] Utilizadores utilizadores)
        {
            if (id != utilizadores.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(utilizadores);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UtilizadoresExists(utilizadores.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(utilizadores);
        }

        // GET: Utilizadores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Utilizadores == null)
            {
                return NotFound();
            }

            var utilizadores = await _context.Utilizadores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (utilizadores == null)
            {
                return NotFound();
            }

            return View(utilizadores);
        }

        // POST: Utilizadores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Utilizadores == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Utilizadores'  is null.");
            }
            var utilizadores = await _context.Utilizadores.FindAsync(id);
            if (utilizadores != null)
            {
                _context.Utilizadores.Remove(utilizadores);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UtilizadoresExists(int id)
        {
          return _context.Utilizadores.Any(e => e.Id == id);
        }
    }
}

Views/Reviews/Create.cshtml
@model AsMinhasReviews.Models.Reviews

@{
    ViewData["Title"] = "Criar review";
}

<h1>Criar review</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Conteudo" class="control-label"></label>
                <textarea asp-for="Conteudo" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Conteudo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JogoFK" class="control-label"></label>
                <select asp-for="JogoFK" class ="form-control" asp-items="ViewBag.JogoFK"></select>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Reviews/Delete.cshtml
@model AsMinhasReviews.Models.Reviews

@{
    ViewData["Title"] = "Remover review";
}
@if (User.IsInRole("Administrador") || User.Identity.Name == Model.Criador.Nome)
{
    <h1>Remover review</h1>
    <h2>Tem a certeza que quer remover a review?</h2>
    <div>
        <hr />
        <table class="table">
            <tr>
                <td style="padding-left:0px; padding-right:8px;">
                    <div class="listarating" style="float: right">@Html.DisplayFor(model => model.Rating) <img src="~/Fotos/estrela.png" height="22.5px" style="margin-bottom:7.5px;" /></div>
                    @{
                        var linkJogo = Model.Jogo.Id;
                    }
                    <div class="listainfo"><a class="listatitulo" style="font-size:20px;" asp-controller="Jogos" asp-action="Details" asp-route-id=@linkJogo>@Html.DisplayFor(model => model.Jogo.Nome)</a></div>
                    @{
                        var linkCriador = Model.Criador.Id;
                    }
                    <div class="listainfo"><a class="listatitulo" style="font-size:15px;" asp-controller="Utilizadores" asp-action="Details" asp-route-id=@linkCriador>@Html.DisplayFor(model => model.Criador.Nome)</a></div>
                    <div class="listadesc">@Html.DisplayFor(model => model.Conteudo)</div>
                    @{
                        var Datalanc = Model.DataCriacao.ToLongDateString();
                    }
                    <div class="listainfo">@Datalanc</div>
                </td>
            </tr>
        </table>
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" />
        </form>
    </div>
}
else
{
    <p>A remoção da review é reservada apenas ao seu criador.</p>
}

Views/Reviews/Details.cshtml
@model AsMinhasReviews.Models.Reviews
@{
    ViewData["Title"] = "Detalhes da review";
}
<div>
    <table class="table">
            <tr>
                <td style="padding-left:0px; padding-right:8px;">
                    <div class="listarating" style="float: right">@Html.DisplayFor(model => model.Rating) <img src="~/Fotos/estrela.png" height="22.5px" style="margin-bottom:7.5px;" /></div>
                    @{var linkJogo = Model.Jogo.Id;}
                    <div class="listainfo"><a class="listatitulo" style="font-size:20px;" asp-controller="Jogos" asp-action="Details" asp-route-id=@linkJogo>@Html.DisplayFor(model => model.Jogo.Nome)</a></div>
                    @{var linkCriador = Model.Criador.Nome;}
                    <div class="listainfo"><a class="listatitulo" style="font-size:15px;" asp-controller="Utilizadores" asp-action="Details" asp-route-id=@linkCriador>@Html.DisplayFor(model => model.Criador.Nome)</a></div>
                    <div class="listadesc">@Html.DisplayFor(model => model.Conteudo)</div>
                    @{var Datalanc = Model.DataCriacao.ToLongDateString();}
                    <div class="listainfo">@Datalanc</div>
                </td>
            </tr>
    </table>
</div>
@if (User.IsInRole("Administrador") || User.Identity.Name == Model.Criador.Nome)
{
    <div>
        <a asp-action="Edit" asp-route-id="@Model?.Id">Editar</a> | 
        <a asp-action="Delete" asp-route-id="@Model?.Id">Remover</a>
    </div>
}

Views/Reviews/Edit.cshtml
@model AsMinhasReviews.Models.Reviews

@{
    ViewData["Title"] = "Editar review";
}
@if (User.IsInRole("Administrador") || User.Identity.Name == Model.Criador.Nome)
{
<h1>Editar review</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Conteudo" class="control-label"></label>
                <textarea asp-for="Conteudo" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Conteudo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div style="visibility:hidden;height:0px;" class="form-group">
                <label style="visibility:hidden;height:0px;" asp-for="JogoFK" class="control-label"></label>
                <select style="visibility:hidden;height:0px;" asp-for="JogoFK" class="form-control" asp-items="ViewBag.JogoFK"></select>
                <span asp-validation-for="JogoFK" class="text-danger"></span>
            </div>
            <div style="visibility:hidden;height:0px;" class="form-group">
                <label style="visibility:hidden;height:0px;" asp-for="CriadorFK" class="control-label"></label>
                <select style="visibility:hidden;height:0px;" asp-for="CriadorFK" class="form-control" asp-items="ViewBag.CriadorFK"></select>
                <span asp-validation-for="CriadorFK" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
}
else
{
    <p>A remoção da review é reservada apenas ao seu criador.</p>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Reviews/Index.cshtml
@model IEnumerable<AsMinhasReviews.Models.Reviews>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DataCriacao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Conteudo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Criador)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Jogo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DataCriacao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Conteudo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Criador.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Jogo.Capa)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>